w1DevicesPath: /sys/bus/w1/devices

dataFile: data.csv

sensor-config:
  schedule: '0 0/15 * * * ?'
  sensors:
  - id: 28-000002c7c3ee
    name: дом
  - id: 28-000002c7d1b5
    name: улица
  - id: 28-000002c7eed3
    name: подвал
  - id: 28-0000066c6a65
    name: крыльцо щит

sms-config:
  inputFolder: /var/spool/gammu/inbox
  outputFolder: /var/spool/gammu/outbox
  processedFolder: /var/spool/gammu/processed
  schedule: '0/15 * * * * ?'
  heatingPin: GPIO_00
  phones:
  - phone: 79210972100
    name: megafon
  - phone: 79112403797
    name: MTS
  - phone: 79119378212
    name: mama

termostat:
  tDay: 12.0
  tNight: 16.0
  delta: 0.5
  nightBegin: 23:10:00
  nightEnd: 7:10:00
  schedule: '0 0/5 * * * ?'
  sensor: 28-000002c7c3ee
  relayPin: GPIO_00