w1DevicesPath: /sys/bus/w1/devices

dataFile: data.csv

sensor-config:
  schedule: '0 0/1 * * * ?'
  sensors:
  - id: 28-000002c7c3ee
    name: house
  - id: 28-031701a152ff
    name: street
  - id: 28-000002c7eed3
    name: basement
  - id: 28-0000058ddc1d
    name: case
  - id: 28-0417019b15ff
    name: veranda
  - id: 28-0317017a6aff
    name: my-room
  - id: 28-0517019b22ff
    name: hot-watter

sms-config:
  inputFolder: /var/spool/gammu/inbox
  outputFolder: /var/spool/gammu/outbox
  processedFolder: /var/spool/gammu/processed
  schedule: '0/15 * * * * ?'
  heatingPin: 'GPIO 0'
  forwardingPhone: 79210972100
  phones:
  - phone: 79210972100
    name: megafon
  - phone: 79112403797
    name: MTS
  - phone: 79119378212
    name: mama

thermostat.schedule: '1/30 * * * * ?'

thermostat-electro:
  tDay: 14.0
  tNight: 16.0
  delta: 0.5
  nightBegin: 23:10:00
  nightEnd: 7:10:00
  sensor: 28-000002c7c3ee
  relayPins: 
  - 'GPIO 0'

voltage-monitor:
  schedule: '0/30 * * * * ?'
  pins:
  - id: 0
    ratio: 0.022573
    unit: V
  - id: 1
    ratio: 0.32573
    unit: V

thermostat-gas:
  tDay: 23.0
  tNight: 20.0
  delta: 0.3
  nightBegin: 21:00:00
  nightEnd: 7:30:00
  sensor: 28-000002c7c3ee
  relayPins: 
  - 'GPIO 1'
  - 'GPIO 4'

thermostat-veranda:
  tDay: 6.5
  tNight: 7.5
  delta: 0.5
  nightBegin: 21:00:00
  nightEnd: 8:00:00
  sensor: 28-0417019b15ff
  relayPins: 
  - 'GPIO 2'

thermostat-veranda-em:
  tDay: 4.0
  tNight: 4.0
  delta: 0.3
  nightBegin: 22:00:00
  nightEnd: 7:00:00
  sensor: 28-0417019b15ff
  relayPins:
  - 'GPIO 1'

thermostat-my-room:
  tDay: 22.5
  tNight: 20.0
  delta: 0.3
  nightBegin: 21:00:00
  nightEnd: 8:00:00
  sensor: 28-0317017a6aff
  relayPins: 
  - 'GPIO 3'
  - 'GPIO 1'

thermostat-hot-watter:
  tDay: 39.0
  tNight: 39.0
  delta: 4.0
  nightBegin: 23:10:00
  nightEnd: 7:10:00
  sensor: 28-0517019b22ff
  relayPins:
    - 'GPIO 6'

button-controller:
  buttonPinName: 'GPIO 5'

relay-aggregator:
  schedule: '5/30 * * * * ?'
  pinAggregates:
    '[GPIO 1]': 3