w1DevicesPath: /sys/bus/w1/devices

dataFile: data.csv

sensor-config:
  schedule: '0 0/15 * * * ?'
  sensors:
  - id: 28-000002c7c3ee
    name: house
  - id: 28-000002c7d1b5
    name: street
  - id: 28-000002c7eed3
    name: basement
#  - id: 28-0000066c6a65
  - id: 28-0000058ddc1d
    name: case

sms-config:
  inputFolder: /var/spool/gammu/inbox
  outputFolder: /var/spool/gammu/outbox
  processedFolder: /var/spool/gammu/processed
  schedule: '0/15 * * * * ?'
  heatingPin: 'GPIO 0'
  forwardingPhone: 79210972100
  phones:
  - phone: 79210972100
    name: megafon
  - phone: 79112403797
    name: MTS
  - phone: 79119378212
    name: mama

termostat:
  tDay: 30.0
  tNight: 30.0
  delta: 0.5
  nightBegin: 23:10:00
  nightEnd: 7:10:00
  schedule: '0 0/5 * * * ?'
  sensor: 28-0000058ddc1d
  relayPin: 'GPIO 0'

voltage-monitor:
  schedule: '0/30 * * * * ?'
  pins:
  - id: 0
    ratio: 0.022573
    unit: V
  - id: 1
    ratio: 0.32573
    unit: V


thermostat-gas:
  tDay: 20.0
  tNight: 18.0
  delta: 0.5
  nightBegin: 22:00:00
  nightEnd: 7:00:00
  schedule: '0/5 * * * * ?'
  sensor: 28-0000058ddc1d
  relayPin: 'GPIO 1'

button-controller:
  buttonPinName: 'GPIO 5'