w1DevicesPath: /sys/bus/w1/devices

sensor-config:
    sensors:
    -
        id: 28-000002c7c3ee
        name: house
    -
        id: 28-000002c7d1b5
        name: street
    -
        id: 28-000002c7eed3
        name: basement
    -
        id: 28-0000066c6a65
        name: case

sms-config:
    inputFolder: /var/spool/gammu/inbox
    outputFolder: /var/spool/gammu/outbox
    processedFolder: /var/spool/gammu/processed

    phones:
    -
        phone: 79210972100
        name: megafon
    -
        phone: 79112403797
        name: MTS
